config/routes.rb
require 'api_subdomain'


Bostonhack::Application.routes.draw do

  get "events/index"

  get "events/show"

  get "comment/show"

  get "search/index"

  get "features/index"

  get "features/show"
  
  
  namespace :v1 do 
    constraints (ApiSubdomain) do
      resources :neighborhoods, :only => [:show,:index]
      resources :open_spaces, :only => [:show,:index]
      resources :features, :only => [:show]
    end
  end

  resources :map
  
  resources :near_me
  
  resources :events

  match "/near", :to =>"near_me#index"  
  
  match "/search", :to =>"search#index"
  
  match "/comment/:id", :to => "comment#show"
  
  resources :open_spaces do |open_space|
    resources :nearby_events
  end
  
  resources :neighborhoods
  resources :features

  get "home/index"
  match "/about", :to => "about#index"
  
  match "/getinvolved", :to => "getinvolved#index"

  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  ###################################
  # AR Plugins/gems
  ###################################
  
  has_attached_file :photo, :styles => {:thumb => "140x140#"}
  
  #Will Paginate
  cattr_reader :per_page
  @@per_page = 10  
  
  ###################################
  # Getters / Setters
  ###################################
  
  ###################################
  # Associations
  ###################################
  has_and_belongs_to_many :open_spaces
  
  ###################################
  # Validations
  ###################################
  
  ###################################
  # Callbacks
  ###################################
  
  ###################################
  # Scopes
  ###################################
  scope :with_open_spaces, joins(:open_spaces).order("start_time asc")
  
  ###################################
  # instance methods
  ###################################
  def timeify(time)
    Time.parse(self.send(time)).utc
  end
  
  ##################################
  # Class Methods
  ##################################
  def self.current
    where("start_time >= ?", Time.now.midnight)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.current.with_open_spaces.order("start_time asc").uniq.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
  
  def start_time_hour(time)
    time.strftime("%l%p")
  end
  
  def human_readable_start_time(time)
    time.strftime("%A, %B #{time.day.ordinalize}")
  end
  
  def events_nav_uri
    "/events"
  end
end

app/views/events/_event.html.haml
%li
  %h3.ui-li-heading=link_to event.name, event_url(event)
  %p.ui-li-disc= human_readable_start_time(event.timeify :start_time)
  %p.ui-li-disc 
    = start_time_hour(event.timeify :start_time)
    \-
    = event.open_spaces.first.name

app/views/events/index.html.haml
%div{"data-role" => "page", "data-backbutton" => "true", "data-theme" => "b"}
  %div{"data-role" => "header", "data-position" => "inline"}
    =render :partial => 'home/title'
  %div{"data-role" => "content"}
    %ul{"data-role" => "listview", "data-inset" => "true"}
      %li{"data-role" => "list-divider"} Events
      = render @events
    = render :partial => "open_spaces/list_navigation", :locals => {:spaces => @events, :base_uri => events_nav_uri}

app/views/events/show.html.haml
%div{"data-role" => "page", "data-backbutton" => "true", "data-theme" => "b"}
  %div{"data-role" => "header", "data-position" => "inline"}
    =render :partial => 'home/title'
  %div{"data-role" => "content"}
    .ui-grid-a
      .ui-block-a
        %p= @event.name
        %p
          = human_readable_start_time(@event.timeify :start_time)
          %br
          - if @event.start_time && @event.end_time
            = start_time_hour(@event.timeify :start_time)
            \-
            = start_time_hour(@event.timeify :end_time)          
        %p
          = link_to @event.open_spaces.first.name, open_space_url(@event.open_spaces.first)
      .ui-block-b
        .rounded_corner
          -if @event.photo?
            = image_tag @event.photo.url(:thumb), :class => "rounded_corner"
          -else
            = image_tag "smith.jpeg", :class => "rounded_corner", :width => 140
    = render :partial => "open_spaces/description", :locals => {:space => @event}