config/routes.rb
require 'api_subdomain'


Bostonhack::Application.routes.draw do

  get "events/index"

  get "events/show"

  get "comment/show"

  get "search/index"

  get "features/index"

  get "features/show"
  
  
  namespace :v1 do 
    constraints (ApiSubdomain) do
      resources :neighborhoods, :only => [:show,:index]
      resources :open_spaces, :only => [:show,:index]
      resources :features, :only => [:show]
    end
  end

  resources :map
  
  resources :near_me
  
  resources :events

  match "/near", :to =>"near_me#index"  
  
  match "/search", :to =>"search#index"
  
  match "/comment/:id", :to => "comment#show"
  
  resources :open_spaces do |open_space|
    resources :nearby_events
  end
  
  resources :neighborhoods
  resources :features

  get "home/index"
  match "/about", :to => "about#index"
  
  match "/getinvolved", :to => "getinvolved#index"

  root :to => "home#index"

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  
  ###################################
  # AR Plugins/gems
  ###################################
  
  #Paperclip
  has_attached_file :photo, :styles => {:thumb => "80x80#"}  
  
  ###################################
  # Getters / Setters
  ###################################
  
  ###################################
  # Associations
  ################################### 
  
  ###################################
  # Validations
  ###################################  
  
  ###################################
  # Callbacks
  ################################### 
  
  ##################################
  # instance methods
  ##################################
  
  ##################################
  # Class Methods
  ##################################  
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  caches_page :index
  
  def index  
    @neighborhoods = Region.ordered_by_name
  end

  def show
    @region = Region.find(params[:id])
    @spaces = OpenSpace.within_neighborhood(@region.id)
    if params[:filter]
      @spaces = @spaces.tagged_with(params[:filter])
    end
    @spaces = @spaces.paginate(:page => params[:page], :per_page => 10)
  end
  
end

app/controllers/v1/neighborhoods_controller.rb
class V1::NeighborhoodsController < V1Controller
  
  respond_to :json
  
  def index
    if params[:lat] && params[:lng]
      regions_list = Region.find_nearby_via_coords(params[:lat], params[:lng])
      @regions = Region.build_feature_collection(regions_list)
    elsif bounding_box
      @regions = build_feature_resource(Region,bounding_box)
    else
      @regions = Region.build_feature_collection
    end
    
    respond_with @regions
  end
  
  def show
    respond_with Region.build_feature_collection(Region.where(:id => params[:id]))
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
  def list_cache_store(id,page,filter)
    ret_val = "neighborhood-#{id}"
    ret_val += "-#{page}" if page
    ret_val += "-#{filter}" if filter
    ret_val
  end
  
  def neighborhood_nav_uri
    "/neighborhoods/#{params[:id]}"
  end
end

app/views/neighborhoods/_neighborhood.html.haml
%li 
  =link_to neighborhood.name, neighborhood_path(neighborhood)
  %span.ui-li-count= neighborhood.open_spaces.count

app/views/neighborhoods/index.html.haml
%div{"data-role" => "page", "data-backbutton" => "true", "data-theme" => "b"}
  %div{"data-role" => "header", "data-position" => "inline"}
    =render :partial => 'home/title'
  %div{"data-role" => "content"}
    %ul{"data-role" => "listview", "data-inset" => "true"}
      %li{"data-role" => "list-divider"} Neighborhoods
      = render :partial => 'neighborhood', :collection => @neighborhoods

app/views/neighborhoods/show.html.haml
#neighborhoodPage{"data-role" => "page", "data-backbutton" => "true", "data-theme" => "b"}
  %div{"data-role" => "header", "data-position" => "inline"}
    =render :partial => 'home/title'
    %a.ui-btn-right{:href => "/map?neighborhood=#{params[:id]}", "data-icon" => "gear", :rel => "external"} Map
  %div{"data-role" => "content"}
    = render :partial => "filters/filters", :locals => {:filters => neighborhood_filter_param(params[:id])}
    %ul{"data-role" => "listview", "data-inset" => "true"}
      %li{"data-role" => "list-divider"}
        =@region.name
        - cache (list_cache_store(params[:id],params[:page],params[:filter])) do
          =render :partial => "open_spaces/open_space", :collection => @spaces, :as => :space
    = render :partial => "open_spaces/list_navigation", :locals => {:spaces => @spaces, :base_uri => neighborhood_nav_uri}